# Generated by Django 4.1.9 on 2023-07-02 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='readings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sensor_data', models.IntegerField(default=0)),
                ('time', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='studentmodel',
            name='mob',
            field=models.CharField(max_length=200),
        ),
    ]
